import express from "express";
import cors from "cors";
import path from "node:path";
import { config } from "./config.js";
import { errorHandler } from "./utils/http.js";
import { authRouter } from "./routes/auth.routes.js";
import { patientRouter } from "./routes/patient.routes.js";
import { appointmentRouter } from "./routes/appointment.routes.js";
import { recordRouter } from "./routes/record.routes.js";
import { documentRouter } from "./routes/document.routes.js";
import { moduleRouter } from "./routes/module.routes.js";
import { aiRouter } from "./routes/ai.routes.js";
import { billingRouter } from "./routes/billing.routes.js";
import { dashboardRouter } from "./routes/dashboard.routes.js";
import { userRouter } from "./routes/user.routes.js";
import { clinicRouter } from "./routes/clinic.routes.js";
import { profileRouter } from "./routes/profile.routes.js";
import { auditRouter } from "./routes/audit.routes.js";
import { accountRouter } from "./routes/account.routes.js";
import { subscriptionRouter } from "./routes/subscription.routes.js";
import { examImageRouter } from "./routes/exam-image.routes.js";
import { moduleWorkspaceRouter } from "./routes/module-workspace.routes.js";
import { customFeatureRouter } from "./routes/custom-feature.routes.js";
import { marketplaceRouter } from "./routes/marketplace.routes.js";
import { platformRouter } from "./routes/platform.routes.js";

export const app = express();

app.use(cors());
app.use("/api/subscription/stripe/webhook", express.raw({ type: "application/json" }));
app.use(express.json({ limit: "1mb" }));
app.use("/uploads", express.static(path.resolve(config.uploadDir)));

app.get("/api/health", (_req, res) => res.json({ ok: true, name: "Odonto Modular AI" }));
app.use("/api/auth", authRouter);
app.use("/api/users", userRouter);
app.use("/api/clinic", clinicRouter);
app.use("/api/profile", profileRouter);
app.use("/api/audit", auditRouter);
app.use("/api/account", accountRouter);
app.use("/api/dashboard", dashboardRouter);
app.use("/api/patients", patientRouter);
app.use("/api/appointments", appointmentRouter);
app.use("/api/records", recordRouter);
app.use("/api/documents", documentRouter);
app.use("/api/exam-images", examImageRouter);
app.use("/api/modules", moduleRouter);
app.use("/api/module-workspace", moduleWorkspaceRouter);
app.use("/api/custom-features", customFeatureRouter);
app.use("/api/marketplace", marketplaceRouter);
app.use("/api/platform", platformRouter);
app.use("/api/ai", aiRouter);
app.use("/api/billing", billingRouter);
app.use("/api/subscription", subscriptionRouter);

app.use(errorHandler);
